### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ljch2018** [GentleZhu/ReMIne#24]
```
g++ -std=c++11 -Wall -O3 -msse2 -fopenmp -I..  -pthread -lm -Wno-unused-result -Wno-sign-compare -Wno-unused-variable -Wno-parentheses -Wno-format -o bin/remine_train src/main.cpp
In file included from src/utils/parameters.h:4:0,
                 from src/main.cpp:1:
src/utils/../utils/utils.h:29:0: warning: ignoring #pragma omp declare [-Wunknown-pragmas]
 #pragma omp declare reduction(vec_double_plus : std::vector<double> : \
 ^
In file included from src/classification/../classification/predict_quality.h:7:0,
                 from src/classification/label_generation.h:8,
                 from src/classification/feature_extraction.h:6,
                 from src/main.cpp:6:
src/classification/../classification/random_forest.h: In member function ‘std::pair<int, double> RandomForestRelated::RandomForest::estimate(std::vector<double>&)’:
src/classification/../classification/random_forest.h:365:46: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, ‘||’, ‘min’ or ‘max’ before ‘vec_double_plus’
         # pragma omp parallel for reduction (vec_double_plus : sum)
                                              ^
make: *** [bin/remine_train] Error 1
```
My g++ version is 4.8. Maybe the OpenMP version is too low in my computer,  would you please show me the right version. Thanks.

**Comment by ljch2018** [comment]
This code works fine on ubuntu 16.04, and maybe not work on centos 7.
